### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by gilleslandais** [pgsphere/pgsphere#4]
Hello,
I would like to install moc pgsphere for tests but the compilation failed:

$ make USE_PGXS=1 PG_CONFIG=/usr/bin/pg_config
g++ -Wall -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -I/usr/include/healpix_cxx  -c -o process_moc.o process_moc.cpp
process_moc.cpp: In function ‘void moc_disc(void*, int, double, double, double, pgs_error_handler)’:
process_moc.cpp:1004:32: error: ‘class rangeset<long int>’ has no member named ‘nranges’
 1004 |   for (tsize j = 0; j < pixset.nranges(); j++)
      |                                ^~~~~~~
process_moc.cpp: In function ‘void moc_polygon(void*, int, int32, float8*, pgs_error_handler)’:
process_moc.cpp:1038:32: error: ‘class rangeset<long int>’ has no member named ‘nranges’
 1038 |   for (tsize j = 0; j < pixset.nranges(); j++)
      |                                ^~~~~~~
make: *** [<commande interne>: process_moc.o] Error 1

Regards,
Gilles Landais (CDS)

**Comment by df7cb** [comment]
Hi Gilles,
which healpix-cxx version is that? The code from the moc branch has been tested with 3.30 (Ubuntu Bionic), 3.50 (Debian Buster), and 3.60 (Debian unstable).
Christoph

**Comment by msdemlei** [comment]
Is that still a problem?  If not, Gilles, could you close this?

**Comment by gilleslandais** [comment]
Hi,

Yes I had some problem with the compilation due (if I remember) to my (old) healpix library .
the OS was an other possibility who could explain the failure (Ubuntu focal)

I will try again with a new healpix library - I would like to test it but I was kept on other subjects..
