### ISSUE TITLE
ISO C90 forbids variable length array ‘arr’ [-Werror=vla]

### ISSUE THREAD

**Issue by joelonsql** [pgsphere/pgsphere#6]
Build fails on Ubuntu 20.04.2 LTS running Ubuntu 13.2-1.pgdg20.04+1:

polygon.c: In function ‘spherepoly_in’:
polygon.c:827:3: error: ISO C90 forbids variable length array ‘arr’ [-Werror=vla]
  827 |   SPoint  arr[nelem];
      |   ^~~~~~
polygon.c: In function ‘spherepoly_area’:
polygon.c:895:2: error: ISO C90 forbids variable length array ‘s’ [-Werror=vla]
  895 |  SPoint  s[poly->npts + 2];
      |  ^~~~~~
cc1: some warnings being treated as errors
make: *** [<builtin>: polygon.o] Error 1

As suggested by @esabol, maybe you could try fixing the build by:

"Anyway, I just wanted to suggest that you try adding -std=c99 to the compilation command for this file or use /usr/bin/c99 instead of gcc."

**Comment by esabol** [comment]
Actually, that suggestion was for you, @joelonsql, to workaround the compilation error. :smile:

**Comment by esabol** [comment]
There's a pull request for this in the akorotkov/pgsphere repo. You can find the patch here:

https://github.com/akorotkov/pgsphere/pull/14/files

Hope this helps!

**Comment by df7cb** [comment]
Closing this one in favor of the other repo(s)
